const { Client, RichEmbed, Message, MessageEmbed } = require('discord.js');
module.exports = function(username,id,avatar) {
    const embed =  new MessageEmbed()
            .setTitle(':page_facing_up: Help PollPy')
            .setColor(0xede905)
            .setDescription(':question: How to use the Prediction/Poll command : :question:')
            .setTimestamp()
            .setAuthor(username, "https://cdn.discordapp.com/avatars/"+id+"/"+avatar+".webp?size=128")
            .addFields(
                { name: 'Admins Commands : \n', value: ':pencil: /pcurrency {type of command} {Tag of User} {Amount Of Modification} \n (Example : /pcurrency |add| |@PollPy| |1000|)\n :exclamation: Conditions : All params are required, You can Add, Remove and Set currency of a user of the server\n\n:gear: /pconfig {Type} [Role] \n (Example : /pconfig |SetAdmin| |@Admin|) \n :exclamation: Conditions : Type is required but Role is only use if they are modifications (not for ViewConfig)\n\n:wrench: /defaultcurrency {Type} {Role} {Amount} \n (Example : /defaultcurrency |SetAdmin| |@Admin| |1000|) \n :exclamation: Conditions : Type, Role and Amount are required'},
                { name: 'Moderators And Admins Commands : \n', value: ':pencil: /poll create {type of poll} {question asked} {choice A} [choice B] [choice C] ...\n (Example : /poll create |Make a Bet| |I will win this one !| |I don\'t think so| |Yes sure !|)\n :exclamation: Conditions : Type, Question and Choice A are required, alternatives choices are conditionnals up to 5. \n **(Prediction that lasts more than 1 week can be ended by a PollPy Admin !)** \n\n :lock: /poll lock {poll ID} \n (Example : /poll lock |37|) \n :exclamation: Be Careful : Will lock the prediction and nobody will be able to interract with except with /poll end \n\n :hourglass: /poll end {poll ID} {Winner Choice} [Reward] \n (Example : /poll end |37| |1| |200|) \n :exclamation: Conditions : ID and Choice are required, reward is only for reward predictions\n\n:newspaper: /plist\n (Example : /plist)\n :exclamation: Give You the list of your Predictions\n\n\n'},
                { name: 'Users, Moderators And Admins Commands : \n', value: ':envelope_with_arrow: /poll select {poll ID} {Choice} [Bet]\n (Example : /poll select |37| |1| |200|) \n :exclamation: Conditions : ID and Choice are required, Bet is only for bet predictions \n\n:desktop: /profile {User Tag} \n (Example : /profile |@PollPy|)\n :exclamation: Conditions : ID and Choice are required, Bet is only for bet predictions\n\n:newspaper: /pinfo\n (Example : /pinfo)\n :exclamation: Give You Informations about the bot\n\n:medal: /leaderboard\n (Example : /leaderboard)\n :exclamation: Give You The Top15 of your Server :'},
                { name: ':envelope: Author Credits : ', value: 'All right reserved to Proxyfil🦄#0001, please contact me for help or come here : https://discord.gg/KqxsnEDVqk or support me on Patreon : https://www.patreon.com/proxyfil'});

    return embed;
}